name: Main

on:
  push:
    branches: '**'
    tags: '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    if: github.repository_owner == 'powerof3'
    uses: adya/pack-skse-mod/.github/workflows/pack.yml@main
    with:
      CMAKE_VR_CONFIG_PRESET: ''
      CMAKE_VR_BUILD_PRESET: ''
      AE_353_BRANCH: master
      AE_353_COMMON_LIB_BRANCH: dev-1.6.640
      FOMOD_INCLUDE_PDB: true
      FOMOD_MOD_NAME: "Seasons of Skyrim SKSE"
      FOMOD_MOD_AUTHOR: "powerofthree"
      FOMOD_MOD_NEXUS_ID: "62861"
      FOMOD_AE353_PATH: 'AE640/SKSE/Plugins'
      FOMOD_AE353_NAME: 'SSE v1.6.640 ("Anniversary Edition")'
      FOMOD_AE353_DESCR: 'Select this if you are using Skyrim Anniversary Edition v1.6.640'
      FOMOD_AE353_MIN_GAME_VERSION: '1.6.640.0'
      FOMOD_AE_NAME: 'SSE v1.6.1130+ ("Anniversary Edition")'
      FOMOD_AE_DESCR: 'Select this if you are using Skyrim Anniversary Edition v1.6.1130 or higher (latest update).'
      FOMOD_AE_MIN_GAME_VERSION: '1.6.1130.0'
      FOMOD_REQUIRED_INSTALLATION_DIR: "Skyrim/Data"
      PUBLISH_ARCHIVE_TYPE: '7z'
      VCPKG_COMMIT_ID: 'fecdd89f28ed883b26a48c2b30085f6384070bb8'
